// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/apptypeprocessor/ent/middlewaredefinition"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/apptypeprocessor/ent/predicate"
)

// MiddlewareDefinitionQuery is the builder for querying MiddlewareDefinition entities.
type MiddlewareDefinitionQuery struct {
	config
	ctx        *QueryContext
	order      []middlewaredefinition.OrderOption
	inters     []Interceptor
	predicates []predicate.MiddlewareDefinition
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MiddlewareDefinitionQuery builder.
func (mdq *MiddlewareDefinitionQuery) Where(ps ...predicate.MiddlewareDefinition) *MiddlewareDefinitionQuery {
	mdq.predicates = append(mdq.predicates, ps...)
	return mdq
}

// Limit the number of records to be returned by this query.
func (mdq *MiddlewareDefinitionQuery) Limit(limit int) *MiddlewareDefinitionQuery {
	mdq.ctx.Limit = &limit
	return mdq
}

// Offset to start from.
func (mdq *MiddlewareDefinitionQuery) Offset(offset int) *MiddlewareDefinitionQuery {
	mdq.ctx.Offset = &offset
	return mdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mdq *MiddlewareDefinitionQuery) Unique(unique bool) *MiddlewareDefinitionQuery {
	mdq.ctx.Unique = &unique
	return mdq
}

// Order specifies how the records should be ordered.
func (mdq *MiddlewareDefinitionQuery) Order(o ...middlewaredefinition.OrderOption) *MiddlewareDefinitionQuery {
	mdq.order = append(mdq.order, o...)
	return mdq
}

// First returns the first MiddlewareDefinition entity from the query.
// Returns a *NotFoundError when no MiddlewareDefinition was found.
func (mdq *MiddlewareDefinitionQuery) First(ctx context.Context) (*MiddlewareDefinition, error) {
	nodes, err := mdq.Limit(1).All(setContextOp(ctx, mdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{middlewaredefinition.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mdq *MiddlewareDefinitionQuery) FirstX(ctx context.Context) *MiddlewareDefinition {
	node, err := mdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MiddlewareDefinition ID from the query.
// Returns a *NotFoundError when no MiddlewareDefinition ID was found.
func (mdq *MiddlewareDefinitionQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = mdq.Limit(1).IDs(setContextOp(ctx, mdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{middlewaredefinition.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mdq *MiddlewareDefinitionQuery) FirstIDX(ctx context.Context) int64 {
	id, err := mdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MiddlewareDefinition entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MiddlewareDefinition entity is found.
// Returns a *NotFoundError when no MiddlewareDefinition entities are found.
func (mdq *MiddlewareDefinitionQuery) Only(ctx context.Context) (*MiddlewareDefinition, error) {
	nodes, err := mdq.Limit(2).All(setContextOp(ctx, mdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{middlewaredefinition.Label}
	default:
		return nil, &NotSingularError{middlewaredefinition.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mdq *MiddlewareDefinitionQuery) OnlyX(ctx context.Context) *MiddlewareDefinition {
	node, err := mdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MiddlewareDefinition ID in the query.
// Returns a *NotSingularError when more than one MiddlewareDefinition ID is found.
// Returns a *NotFoundError when no entities are found.
func (mdq *MiddlewareDefinitionQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = mdq.Limit(2).IDs(setContextOp(ctx, mdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{middlewaredefinition.Label}
	default:
		err = &NotSingularError{middlewaredefinition.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mdq *MiddlewareDefinitionQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := mdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MiddlewareDefinitions.
func (mdq *MiddlewareDefinitionQuery) All(ctx context.Context) ([]*MiddlewareDefinition, error) {
	ctx = setContextOp(ctx, mdq.ctx, "All")
	if err := mdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MiddlewareDefinition, *MiddlewareDefinitionQuery]()
	return withInterceptors[[]*MiddlewareDefinition](ctx, mdq, qr, mdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mdq *MiddlewareDefinitionQuery) AllX(ctx context.Context) []*MiddlewareDefinition {
	nodes, err := mdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MiddlewareDefinition IDs.
func (mdq *MiddlewareDefinitionQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if mdq.ctx.Unique == nil && mdq.path != nil {
		mdq.Unique(true)
	}
	ctx = setContextOp(ctx, mdq.ctx, "IDs")
	if err = mdq.Select(middlewaredefinition.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mdq *MiddlewareDefinitionQuery) IDsX(ctx context.Context) []int64 {
	ids, err := mdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mdq *MiddlewareDefinitionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mdq.ctx, "Count")
	if err := mdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mdq, querierCount[*MiddlewareDefinitionQuery](), mdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mdq *MiddlewareDefinitionQuery) CountX(ctx context.Context) int {
	count, err := mdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mdq *MiddlewareDefinitionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mdq.ctx, "Exist")
	switch _, err := mdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mdq *MiddlewareDefinitionQuery) ExistX(ctx context.Context) bool {
	exist, err := mdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MiddlewareDefinitionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mdq *MiddlewareDefinitionQuery) Clone() *MiddlewareDefinitionQuery {
	if mdq == nil {
		return nil
	}
	return &MiddlewareDefinitionQuery{
		config:     mdq.config,
		ctx:        mdq.ctx.Clone(),
		order:      append([]middlewaredefinition.OrderOption{}, mdq.order...),
		inters:     append([]Interceptor{}, mdq.inters...),
		predicates: append([]predicate.MiddlewareDefinition{}, mdq.predicates...),
		// clone intermediate query.
		sql:  mdq.sql.Clone(),
		path: mdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MiddlewareDefinition.Query().
//		GroupBy(middlewaredefinition.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mdq *MiddlewareDefinitionQuery) GroupBy(field string, fields ...string) *MiddlewareDefinitionGroupBy {
	mdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MiddlewareDefinitionGroupBy{build: mdq}
	grbuild.flds = &mdq.ctx.Fields
	grbuild.label = middlewaredefinition.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.MiddlewareDefinition.Query().
//		Select(middlewaredefinition.FieldName).
//		Scan(ctx, &v)
func (mdq *MiddlewareDefinitionQuery) Select(fields ...string) *MiddlewareDefinitionSelect {
	mdq.ctx.Fields = append(mdq.ctx.Fields, fields...)
	sbuild := &MiddlewareDefinitionSelect{MiddlewareDefinitionQuery: mdq}
	sbuild.label = middlewaredefinition.Label
	sbuild.flds, sbuild.scan = &mdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MiddlewareDefinitionSelect configured with the given aggregations.
func (mdq *MiddlewareDefinitionQuery) Aggregate(fns ...AggregateFunc) *MiddlewareDefinitionSelect {
	return mdq.Select().Aggregate(fns...)
}

func (mdq *MiddlewareDefinitionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mdq); err != nil {
				return err
			}
		}
	}
	for _, f := range mdq.ctx.Fields {
		if !middlewaredefinition.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mdq.path != nil {
		prev, err := mdq.path(ctx)
		if err != nil {
			return err
		}
		mdq.sql = prev
	}
	return nil
}

func (mdq *MiddlewareDefinitionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MiddlewareDefinition, error) {
	var (
		nodes = []*MiddlewareDefinition{}
		_spec = mdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MiddlewareDefinition).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MiddlewareDefinition{config: mdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mdq *MiddlewareDefinitionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mdq.querySpec()
	_spec.Node.Columns = mdq.ctx.Fields
	if len(mdq.ctx.Fields) > 0 {
		_spec.Unique = mdq.ctx.Unique != nil && *mdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mdq.driver, _spec)
}

func (mdq *MiddlewareDefinitionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(middlewaredefinition.Table, middlewaredefinition.Columns, sqlgraph.NewFieldSpec(middlewaredefinition.FieldID, field.TypeInt64))
	_spec.From = mdq.sql
	if unique := mdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mdq.path != nil {
		_spec.Unique = true
	}
	if fields := mdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, middlewaredefinition.FieldID)
		for i := range fields {
			if fields[i] != middlewaredefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mdq *MiddlewareDefinitionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mdq.driver.Dialect())
	t1 := builder.Table(middlewaredefinition.Table)
	columns := mdq.ctx.Fields
	if len(columns) == 0 {
		columns = middlewaredefinition.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mdq.sql != nil {
		selector = mdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mdq.ctx.Unique != nil && *mdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mdq.predicates {
		p(selector)
	}
	for _, p := range mdq.order {
		p(selector)
	}
	if offset := mdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MiddlewareDefinitionGroupBy is the group-by builder for MiddlewareDefinition entities.
type MiddlewareDefinitionGroupBy struct {
	selector
	build *MiddlewareDefinitionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mdgb *MiddlewareDefinitionGroupBy) Aggregate(fns ...AggregateFunc) *MiddlewareDefinitionGroupBy {
	mdgb.fns = append(mdgb.fns, fns...)
	return mdgb
}

// Scan applies the selector query and scans the result into the given value.
func (mdgb *MiddlewareDefinitionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mdgb.build.ctx, "GroupBy")
	if err := mdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MiddlewareDefinitionQuery, *MiddlewareDefinitionGroupBy](ctx, mdgb.build, mdgb, mdgb.build.inters, v)
}

func (mdgb *MiddlewareDefinitionGroupBy) sqlScan(ctx context.Context, root *MiddlewareDefinitionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mdgb.fns))
	for _, fn := range mdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mdgb.flds)+len(mdgb.fns))
		for _, f := range *mdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MiddlewareDefinitionSelect is the builder for selecting fields of MiddlewareDefinition entities.
type MiddlewareDefinitionSelect struct {
	*MiddlewareDefinitionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mds *MiddlewareDefinitionSelect) Aggregate(fns ...AggregateFunc) *MiddlewareDefinitionSelect {
	mds.fns = append(mds.fns, fns...)
	return mds
}

// Scan applies the selector query and scans the result into the given value.
func (mds *MiddlewareDefinitionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mds.ctx, "Select")
	if err := mds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MiddlewareDefinitionQuery, *MiddlewareDefinitionSelect](ctx, mds.MiddlewareDefinitionQuery, mds, mds.inters, v)
}

func (mds *MiddlewareDefinitionSelect) sqlScan(ctx context.Context, root *MiddlewareDefinitionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mds.fns))
	for _, fn := range mds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
