// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/apptypeprocessor/ent/schema"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/apptypeprocessor/ent/softwaredefinition"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	softwaredefinitionFields := schema.SoftwareDefinition{}.Fields()
	_ = softwaredefinitionFields
	// softwaredefinitionDescName is the schema descriptor for name field.
	softwaredefinitionDescName := softwaredefinitionFields[1].Descriptor()
	// softwaredefinition.NameValidator is a validator for the "name" field. It is called by the builders before save.
	softwaredefinition.NameValidator = func() func(string) error {
		validators := softwaredefinitionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// softwaredefinitionDescIsValid is the schema descriptor for is_valid field.
	softwaredefinitionDescIsValid := softwaredefinitionFields[4].Descriptor()
	// softwaredefinition.DefaultIsValid holds the default value on creation for the is_valid field.
	softwaredefinition.DefaultIsValid = softwaredefinitionDescIsValid.Default.(int)
	// softwaredefinitionDescCreateTime is the schema descriptor for create_time field.
	softwaredefinitionDescCreateTime := softwaredefinitionFields[5].Descriptor()
	// softwaredefinition.DefaultCreateTime holds the default value on creation for the create_time field.
	softwaredefinition.DefaultCreateTime = softwaredefinitionDescCreateTime.Default.(func() time.Time)
	// softwaredefinitionDescUpdateTime is the schema descriptor for update_time field.
	softwaredefinitionDescUpdateTime := softwaredefinitionFields[6].Descriptor()
	// softwaredefinition.DefaultUpdateTime holds the default value on creation for the update_time field.
	softwaredefinition.DefaultUpdateTime = softwaredefinitionDescUpdateTime.Default.(func() time.Time)
	// softwaredefinitionDescID is the schema descriptor for id field.
	softwaredefinitionDescID := softwaredefinitionFields[0].Descriptor()
	// softwaredefinition.IDValidator is a validator for the "id" field. It is called by the builders before save.
	softwaredefinition.IDValidator = softwaredefinitionDescID.Validators[0].(func(int64) error)
}
