// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SoftwareDefinition is the predicate function for softwaredefinition builders.
type SoftwareDefinition func(*sql.Selector)
