// Code generated by ent, DO NOT EDIT.

package spanaggregation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/teanoon/opentelemetry-collector-contrib/exporter/spanaggregationexporter/ent/predicate"
	"github.com/teanoon/opentelemetry-collector-contrib/exporter/spanaggregationexporter/ent/schema"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContainsFold(FieldID, id))
}

// Timestamp applies equality check predicate on the "Timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldTimestamp, v))
}

// TraceId applies equality check predicate on the "TraceId" field. It's identical to TraceIdEQ.
func TraceId(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldTraceId, v))
}

// ParentSpanId applies equality check predicate on the "ParentSpanId" field. It's identical to ParentSpanIdEQ.
func ParentSpanId(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldParentSpanId, v))
}

// PlatformName applies equality check predicate on the "PlatformName" field. It's identical to PlatformNameEQ.
func PlatformName(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldPlatformName, v))
}

// RootServiceName applies equality check predicate on the "RootServiceName" field. It's identical to RootServiceNameEQ.
func RootServiceName(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldRootServiceName, v))
}

// RootSpanName applies equality check predicate on the "RootSpanName" field. It's identical to RootSpanNameEQ.
func RootSpanName(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldRootSpanName, v))
}

// ServiceName applies equality check predicate on the "ServiceName" field. It's identical to ServiceNameEQ.
func ServiceName(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldServiceName, v))
}

// SpanName applies equality check predicate on the "SpanName" field. It's identical to SpanNameEQ.
func SpanName(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldSpanName, v))
}

// ResourceAttributes applies equality check predicate on the "ResourceAttributes" field. It's identical to ResourceAttributesEQ.
func ResourceAttributes(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldResourceAttributes, v))
}

// SpanAttributes applies equality check predicate on the "SpanAttributes" field. It's identical to SpanAttributesEQ.
func SpanAttributes(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldSpanAttributes, v))
}

// Duration applies equality check predicate on the "Duration" field. It's identical to DurationEQ.
func Duration(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldDuration, v))
}

// Gap applies equality check predicate on the "Gap" field. It's identical to GapEQ.
func Gap(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldGap, v))
}

// SelfDuration applies equality check predicate on the "SelfDuration" field. It's identical to SelfDurationEQ.
func SelfDuration(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldSelfDuration, v))
}

// TimestampEQ applies the EQ predicate on the "Timestamp" field.
func TimestampEQ(v time.Time) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "Timestamp" field.
func TimestampNEQ(v time.Time) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "Timestamp" field.
func TimestampIn(vs ...time.Time) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "Timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "Timestamp" field.
func TimestampGT(v time.Time) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "Timestamp" field.
func TimestampGTE(v time.Time) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "Timestamp" field.
func TimestampLT(v time.Time) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "Timestamp" field.
func TimestampLTE(v time.Time) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldTimestamp, v))
}

// TraceIdEQ applies the EQ predicate on the "TraceId" field.
func TraceIdEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldTraceId, v))
}

// TraceIdNEQ applies the NEQ predicate on the "TraceId" field.
func TraceIdNEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldTraceId, v))
}

// TraceIdIn applies the In predicate on the "TraceId" field.
func TraceIdIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldTraceId, vs...))
}

// TraceIdNotIn applies the NotIn predicate on the "TraceId" field.
func TraceIdNotIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldTraceId, vs...))
}

// TraceIdGT applies the GT predicate on the "TraceId" field.
func TraceIdGT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldTraceId, v))
}

// TraceIdGTE applies the GTE predicate on the "TraceId" field.
func TraceIdGTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldTraceId, v))
}

// TraceIdLT applies the LT predicate on the "TraceId" field.
func TraceIdLT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldTraceId, v))
}

// TraceIdLTE applies the LTE predicate on the "TraceId" field.
func TraceIdLTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldTraceId, v))
}

// TraceIdContains applies the Contains predicate on the "TraceId" field.
func TraceIdContains(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContains(FieldTraceId, v))
}

// TraceIdHasPrefix applies the HasPrefix predicate on the "TraceId" field.
func TraceIdHasPrefix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasPrefix(FieldTraceId, v))
}

// TraceIdHasSuffix applies the HasSuffix predicate on the "TraceId" field.
func TraceIdHasSuffix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasSuffix(FieldTraceId, v))
}

// TraceIdEqualFold applies the EqualFold predicate on the "TraceId" field.
func TraceIdEqualFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEqualFold(FieldTraceId, v))
}

// TraceIdContainsFold applies the ContainsFold predicate on the "TraceId" field.
func TraceIdContainsFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContainsFold(FieldTraceId, v))
}

// ParentSpanIdEQ applies the EQ predicate on the "ParentSpanId" field.
func ParentSpanIdEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldParentSpanId, v))
}

// ParentSpanIdNEQ applies the NEQ predicate on the "ParentSpanId" field.
func ParentSpanIdNEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldParentSpanId, v))
}

// ParentSpanIdIn applies the In predicate on the "ParentSpanId" field.
func ParentSpanIdIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldParentSpanId, vs...))
}

// ParentSpanIdNotIn applies the NotIn predicate on the "ParentSpanId" field.
func ParentSpanIdNotIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldParentSpanId, vs...))
}

// ParentSpanIdGT applies the GT predicate on the "ParentSpanId" field.
func ParentSpanIdGT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldParentSpanId, v))
}

// ParentSpanIdGTE applies the GTE predicate on the "ParentSpanId" field.
func ParentSpanIdGTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldParentSpanId, v))
}

// ParentSpanIdLT applies the LT predicate on the "ParentSpanId" field.
func ParentSpanIdLT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldParentSpanId, v))
}

// ParentSpanIdLTE applies the LTE predicate on the "ParentSpanId" field.
func ParentSpanIdLTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldParentSpanId, v))
}

// ParentSpanIdContains applies the Contains predicate on the "ParentSpanId" field.
func ParentSpanIdContains(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContains(FieldParentSpanId, v))
}

// ParentSpanIdHasPrefix applies the HasPrefix predicate on the "ParentSpanId" field.
func ParentSpanIdHasPrefix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasPrefix(FieldParentSpanId, v))
}

// ParentSpanIdHasSuffix applies the HasSuffix predicate on the "ParentSpanId" field.
func ParentSpanIdHasSuffix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasSuffix(FieldParentSpanId, v))
}

// ParentSpanIdEqualFold applies the EqualFold predicate on the "ParentSpanId" field.
func ParentSpanIdEqualFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEqualFold(FieldParentSpanId, v))
}

// ParentSpanIdContainsFold applies the ContainsFold predicate on the "ParentSpanId" field.
func ParentSpanIdContainsFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContainsFold(FieldParentSpanId, v))
}

// PlatformNameEQ applies the EQ predicate on the "PlatformName" field.
func PlatformNameEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldPlatformName, v))
}

// PlatformNameNEQ applies the NEQ predicate on the "PlatformName" field.
func PlatformNameNEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldPlatformName, v))
}

// PlatformNameIn applies the In predicate on the "PlatformName" field.
func PlatformNameIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldPlatformName, vs...))
}

// PlatformNameNotIn applies the NotIn predicate on the "PlatformName" field.
func PlatformNameNotIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldPlatformName, vs...))
}

// PlatformNameGT applies the GT predicate on the "PlatformName" field.
func PlatformNameGT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldPlatformName, v))
}

// PlatformNameGTE applies the GTE predicate on the "PlatformName" field.
func PlatformNameGTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldPlatformName, v))
}

// PlatformNameLT applies the LT predicate on the "PlatformName" field.
func PlatformNameLT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldPlatformName, v))
}

// PlatformNameLTE applies the LTE predicate on the "PlatformName" field.
func PlatformNameLTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldPlatformName, v))
}

// PlatformNameContains applies the Contains predicate on the "PlatformName" field.
func PlatformNameContains(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContains(FieldPlatformName, v))
}

// PlatformNameHasPrefix applies the HasPrefix predicate on the "PlatformName" field.
func PlatformNameHasPrefix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasPrefix(FieldPlatformName, v))
}

// PlatformNameHasSuffix applies the HasSuffix predicate on the "PlatformName" field.
func PlatformNameHasSuffix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasSuffix(FieldPlatformName, v))
}

// PlatformNameEqualFold applies the EqualFold predicate on the "PlatformName" field.
func PlatformNameEqualFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEqualFold(FieldPlatformName, v))
}

// PlatformNameContainsFold applies the ContainsFold predicate on the "PlatformName" field.
func PlatformNameContainsFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContainsFold(FieldPlatformName, v))
}

// RootServiceNameEQ applies the EQ predicate on the "RootServiceName" field.
func RootServiceNameEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldRootServiceName, v))
}

// RootServiceNameNEQ applies the NEQ predicate on the "RootServiceName" field.
func RootServiceNameNEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldRootServiceName, v))
}

// RootServiceNameIn applies the In predicate on the "RootServiceName" field.
func RootServiceNameIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldRootServiceName, vs...))
}

// RootServiceNameNotIn applies the NotIn predicate on the "RootServiceName" field.
func RootServiceNameNotIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldRootServiceName, vs...))
}

// RootServiceNameGT applies the GT predicate on the "RootServiceName" field.
func RootServiceNameGT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldRootServiceName, v))
}

// RootServiceNameGTE applies the GTE predicate on the "RootServiceName" field.
func RootServiceNameGTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldRootServiceName, v))
}

// RootServiceNameLT applies the LT predicate on the "RootServiceName" field.
func RootServiceNameLT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldRootServiceName, v))
}

// RootServiceNameLTE applies the LTE predicate on the "RootServiceName" field.
func RootServiceNameLTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldRootServiceName, v))
}

// RootServiceNameContains applies the Contains predicate on the "RootServiceName" field.
func RootServiceNameContains(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContains(FieldRootServiceName, v))
}

// RootServiceNameHasPrefix applies the HasPrefix predicate on the "RootServiceName" field.
func RootServiceNameHasPrefix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasPrefix(FieldRootServiceName, v))
}

// RootServiceNameHasSuffix applies the HasSuffix predicate on the "RootServiceName" field.
func RootServiceNameHasSuffix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasSuffix(FieldRootServiceName, v))
}

// RootServiceNameIsNil applies the IsNil predicate on the "RootServiceName" field.
func RootServiceNameIsNil() predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIsNull(FieldRootServiceName))
}

// RootServiceNameNotNil applies the NotNil predicate on the "RootServiceName" field.
func RootServiceNameNotNil() predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotNull(FieldRootServiceName))
}

// RootServiceNameEqualFold applies the EqualFold predicate on the "RootServiceName" field.
func RootServiceNameEqualFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEqualFold(FieldRootServiceName, v))
}

// RootServiceNameContainsFold applies the ContainsFold predicate on the "RootServiceName" field.
func RootServiceNameContainsFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContainsFold(FieldRootServiceName, v))
}

// RootSpanNameEQ applies the EQ predicate on the "RootSpanName" field.
func RootSpanNameEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldRootSpanName, v))
}

// RootSpanNameNEQ applies the NEQ predicate on the "RootSpanName" field.
func RootSpanNameNEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldRootSpanName, v))
}

// RootSpanNameIn applies the In predicate on the "RootSpanName" field.
func RootSpanNameIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldRootSpanName, vs...))
}

// RootSpanNameNotIn applies the NotIn predicate on the "RootSpanName" field.
func RootSpanNameNotIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldRootSpanName, vs...))
}

// RootSpanNameGT applies the GT predicate on the "RootSpanName" field.
func RootSpanNameGT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldRootSpanName, v))
}

// RootSpanNameGTE applies the GTE predicate on the "RootSpanName" field.
func RootSpanNameGTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldRootSpanName, v))
}

// RootSpanNameLT applies the LT predicate on the "RootSpanName" field.
func RootSpanNameLT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldRootSpanName, v))
}

// RootSpanNameLTE applies the LTE predicate on the "RootSpanName" field.
func RootSpanNameLTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldRootSpanName, v))
}

// RootSpanNameContains applies the Contains predicate on the "RootSpanName" field.
func RootSpanNameContains(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContains(FieldRootSpanName, v))
}

// RootSpanNameHasPrefix applies the HasPrefix predicate on the "RootSpanName" field.
func RootSpanNameHasPrefix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasPrefix(FieldRootSpanName, v))
}

// RootSpanNameHasSuffix applies the HasSuffix predicate on the "RootSpanName" field.
func RootSpanNameHasSuffix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasSuffix(FieldRootSpanName, v))
}

// RootSpanNameIsNil applies the IsNil predicate on the "RootSpanName" field.
func RootSpanNameIsNil() predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIsNull(FieldRootSpanName))
}

// RootSpanNameNotNil applies the NotNil predicate on the "RootSpanName" field.
func RootSpanNameNotNil() predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotNull(FieldRootSpanName))
}

// RootSpanNameEqualFold applies the EqualFold predicate on the "RootSpanName" field.
func RootSpanNameEqualFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEqualFold(FieldRootSpanName, v))
}

// RootSpanNameContainsFold applies the ContainsFold predicate on the "RootSpanName" field.
func RootSpanNameContainsFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContainsFold(FieldRootSpanName, v))
}

// ServiceNameEQ applies the EQ predicate on the "ServiceName" field.
func ServiceNameEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldServiceName, v))
}

// ServiceNameNEQ applies the NEQ predicate on the "ServiceName" field.
func ServiceNameNEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldServiceName, v))
}

// ServiceNameIn applies the In predicate on the "ServiceName" field.
func ServiceNameIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldServiceName, vs...))
}

// ServiceNameNotIn applies the NotIn predicate on the "ServiceName" field.
func ServiceNameNotIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldServiceName, vs...))
}

// ServiceNameGT applies the GT predicate on the "ServiceName" field.
func ServiceNameGT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldServiceName, v))
}

// ServiceNameGTE applies the GTE predicate on the "ServiceName" field.
func ServiceNameGTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldServiceName, v))
}

// ServiceNameLT applies the LT predicate on the "ServiceName" field.
func ServiceNameLT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldServiceName, v))
}

// ServiceNameLTE applies the LTE predicate on the "ServiceName" field.
func ServiceNameLTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldServiceName, v))
}

// ServiceNameContains applies the Contains predicate on the "ServiceName" field.
func ServiceNameContains(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContains(FieldServiceName, v))
}

// ServiceNameHasPrefix applies the HasPrefix predicate on the "ServiceName" field.
func ServiceNameHasPrefix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasPrefix(FieldServiceName, v))
}

// ServiceNameHasSuffix applies the HasSuffix predicate on the "ServiceName" field.
func ServiceNameHasSuffix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasSuffix(FieldServiceName, v))
}

// ServiceNameEqualFold applies the EqualFold predicate on the "ServiceName" field.
func ServiceNameEqualFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEqualFold(FieldServiceName, v))
}

// ServiceNameContainsFold applies the ContainsFold predicate on the "ServiceName" field.
func ServiceNameContainsFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContainsFold(FieldServiceName, v))
}

// SpanNameEQ applies the EQ predicate on the "SpanName" field.
func SpanNameEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldSpanName, v))
}

// SpanNameNEQ applies the NEQ predicate on the "SpanName" field.
func SpanNameNEQ(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldSpanName, v))
}

// SpanNameIn applies the In predicate on the "SpanName" field.
func SpanNameIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldSpanName, vs...))
}

// SpanNameNotIn applies the NotIn predicate on the "SpanName" field.
func SpanNameNotIn(vs ...string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldSpanName, vs...))
}

// SpanNameGT applies the GT predicate on the "SpanName" field.
func SpanNameGT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldSpanName, v))
}

// SpanNameGTE applies the GTE predicate on the "SpanName" field.
func SpanNameGTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldSpanName, v))
}

// SpanNameLT applies the LT predicate on the "SpanName" field.
func SpanNameLT(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldSpanName, v))
}

// SpanNameLTE applies the LTE predicate on the "SpanName" field.
func SpanNameLTE(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldSpanName, v))
}

// SpanNameContains applies the Contains predicate on the "SpanName" field.
func SpanNameContains(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContains(FieldSpanName, v))
}

// SpanNameHasPrefix applies the HasPrefix predicate on the "SpanName" field.
func SpanNameHasPrefix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasPrefix(FieldSpanName, v))
}

// SpanNameHasSuffix applies the HasSuffix predicate on the "SpanName" field.
func SpanNameHasSuffix(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldHasSuffix(FieldSpanName, v))
}

// SpanNameEqualFold applies the EqualFold predicate on the "SpanName" field.
func SpanNameEqualFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEqualFold(FieldSpanName, v))
}

// SpanNameContainsFold applies the ContainsFold predicate on the "SpanName" field.
func SpanNameContainsFold(v string) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldContainsFold(FieldSpanName, v))
}

// ResourceAttributesEQ applies the EQ predicate on the "ResourceAttributes" field.
func ResourceAttributesEQ(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldResourceAttributes, v))
}

// ResourceAttributesNEQ applies the NEQ predicate on the "ResourceAttributes" field.
func ResourceAttributesNEQ(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldResourceAttributes, v))
}

// ResourceAttributesIn applies the In predicate on the "ResourceAttributes" field.
func ResourceAttributesIn(vs ...*schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldResourceAttributes, vs...))
}

// ResourceAttributesNotIn applies the NotIn predicate on the "ResourceAttributes" field.
func ResourceAttributesNotIn(vs ...*schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldResourceAttributes, vs...))
}

// ResourceAttributesGT applies the GT predicate on the "ResourceAttributes" field.
func ResourceAttributesGT(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldResourceAttributes, v))
}

// ResourceAttributesGTE applies the GTE predicate on the "ResourceAttributes" field.
func ResourceAttributesGTE(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldResourceAttributes, v))
}

// ResourceAttributesLT applies the LT predicate on the "ResourceAttributes" field.
func ResourceAttributesLT(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldResourceAttributes, v))
}

// ResourceAttributesLTE applies the LTE predicate on the "ResourceAttributes" field.
func ResourceAttributesLTE(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldResourceAttributes, v))
}

// SpanAttributesEQ applies the EQ predicate on the "SpanAttributes" field.
func SpanAttributesEQ(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldSpanAttributes, v))
}

// SpanAttributesNEQ applies the NEQ predicate on the "SpanAttributes" field.
func SpanAttributesNEQ(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldSpanAttributes, v))
}

// SpanAttributesIn applies the In predicate on the "SpanAttributes" field.
func SpanAttributesIn(vs ...*schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldSpanAttributes, vs...))
}

// SpanAttributesNotIn applies the NotIn predicate on the "SpanAttributes" field.
func SpanAttributesNotIn(vs ...*schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldSpanAttributes, vs...))
}

// SpanAttributesGT applies the GT predicate on the "SpanAttributes" field.
func SpanAttributesGT(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldSpanAttributes, v))
}

// SpanAttributesGTE applies the GTE predicate on the "SpanAttributes" field.
func SpanAttributesGTE(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldSpanAttributes, v))
}

// SpanAttributesLT applies the LT predicate on the "SpanAttributes" field.
func SpanAttributesLT(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldSpanAttributes, v))
}

// SpanAttributesLTE applies the LTE predicate on the "SpanAttributes" field.
func SpanAttributesLTE(v *schema.Attributes) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldSpanAttributes, v))
}

// DurationEQ applies the EQ predicate on the "Duration" field.
func DurationEQ(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldDuration, v))
}

// DurationNEQ applies the NEQ predicate on the "Duration" field.
func DurationNEQ(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldDuration, v))
}

// DurationIn applies the In predicate on the "Duration" field.
func DurationIn(vs ...int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldDuration, vs...))
}

// DurationNotIn applies the NotIn predicate on the "Duration" field.
func DurationNotIn(vs ...int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldDuration, vs...))
}

// DurationGT applies the GT predicate on the "Duration" field.
func DurationGT(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldDuration, v))
}

// DurationGTE applies the GTE predicate on the "Duration" field.
func DurationGTE(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldDuration, v))
}

// DurationLT applies the LT predicate on the "Duration" field.
func DurationLT(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldDuration, v))
}

// DurationLTE applies the LTE predicate on the "Duration" field.
func DurationLTE(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldDuration, v))
}

// GapEQ applies the EQ predicate on the "Gap" field.
func GapEQ(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldGap, v))
}

// GapNEQ applies the NEQ predicate on the "Gap" field.
func GapNEQ(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldGap, v))
}

// GapIn applies the In predicate on the "Gap" field.
func GapIn(vs ...int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldGap, vs...))
}

// GapNotIn applies the NotIn predicate on the "Gap" field.
func GapNotIn(vs ...int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldGap, vs...))
}

// GapGT applies the GT predicate on the "Gap" field.
func GapGT(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldGap, v))
}

// GapGTE applies the GTE predicate on the "Gap" field.
func GapGTE(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldGap, v))
}

// GapLT applies the LT predicate on the "Gap" field.
func GapLT(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldGap, v))
}

// GapLTE applies the LTE predicate on the "Gap" field.
func GapLTE(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldGap, v))
}

// SelfDurationEQ applies the EQ predicate on the "SelfDuration" field.
func SelfDurationEQ(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldEQ(FieldSelfDuration, v))
}

// SelfDurationNEQ applies the NEQ predicate on the "SelfDuration" field.
func SelfDurationNEQ(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNEQ(FieldSelfDuration, v))
}

// SelfDurationIn applies the In predicate on the "SelfDuration" field.
func SelfDurationIn(vs ...int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldIn(FieldSelfDuration, vs...))
}

// SelfDurationNotIn applies the NotIn predicate on the "SelfDuration" field.
func SelfDurationNotIn(vs ...int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldNotIn(FieldSelfDuration, vs...))
}

// SelfDurationGT applies the GT predicate on the "SelfDuration" field.
func SelfDurationGT(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGT(FieldSelfDuration, v))
}

// SelfDurationGTE applies the GTE predicate on the "SelfDuration" field.
func SelfDurationGTE(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldGTE(FieldSelfDuration, v))
}

// SelfDurationLT applies the LT predicate on the "SelfDuration" field.
func SelfDurationLT(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLT(FieldSelfDuration, v))
}

// SelfDurationLTE applies the LTE predicate on the "SelfDuration" field.
func SelfDurationLTE(v int64) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.FieldLTE(FieldSelfDuration, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SpanAggregation) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SpanAggregation) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SpanAggregation) predicate.SpanAggregation {
	return predicate.SpanAggregation(sql.NotPredicates(p))
}
