// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TbExceptionCategoryColumns holds the columns for the "tb_exception_category" table.
	TbExceptionCategoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "is_valid", Type: field.TypeInt, Default: 1},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
	}
	// TbExceptionCategoryTable holds the schema information for the "tb_exception_category" table.
	TbExceptionCategoryTable = &schema.Table{
		Name:       "tb_exception_category",
		Columns:    TbExceptionCategoryColumns,
		PrimaryKey: []*schema.Column{TbExceptionCategoryColumns[0]},
	}
	// TbExceptionDefineColumns holds the columns for the "tb_exception_define" table.
	TbExceptionDefineColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "short_name", Type: field.TypeString, Size: 100},
		{Name: "long_name", Type: field.TypeString, Size: 2147483647},
		{Name: "related_middleware_id", Type: field.TypeInt64, Nullable: true},
		{Name: "related_middleware_conditions", Type: field.TypeJSON, Nullable: true},
		{Name: "is_valid", Type: field.TypeInt, Default: 1},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "category_id", Type: field.TypeInt64},
	}
	// TbExceptionDefineTable holds the schema information for the "tb_exception_define" table.
	TbExceptionDefineTable = &schema.Table{
		Name:       "tb_exception_define",
		Columns:    TbExceptionDefineColumns,
		PrimaryKey: []*schema.Column{TbExceptionDefineColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tb_exception_define_tb_exception_category_exception_definitions",
				Columns:    []*schema.Column{TbExceptionDefineColumns[8]},
				RefColumns: []*schema.Column{TbExceptionCategoryColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TbExceptionCategoryTable,
		TbExceptionDefineTable,
	}
)

func init() {
	TbExceptionCategoryTable.Annotation = &entsql.Annotation{
		Table: "tb_exception_category",
	}
	TbExceptionDefineTable.ForeignKeys[0].RefTable = TbExceptionCategoryTable
	TbExceptionDefineTable.Annotation = &entsql.Annotation{
		Table: "tb_exception_define",
	}
}
