// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OtelSpanFaultsColumns holds the columns for the "otel_span_faults" table.
	OtelSpanFaultsColumns = []*schema.Column{
		{Name: "SpanId", Type: field.TypeString},
		{Name: "Timestamp", Type: field.TypeTime, Nullable: true},
		{Name: "TraceId", Type: field.TypeString},
		{Name: "PlatformName", Type: field.TypeString},
		{Name: "ClusterName", Type: field.TypeString},
		{Name: "InstanceName", Type: field.TypeString},
		{Name: "RootServiceName", Type: field.TypeString, Nullable: true},
		{Name: "RootSpanName", Type: field.TypeString, Nullable: true},
		{Name: "ParentSpanId", Type: field.TypeString},
		{Name: "ServiceName", Type: field.TypeString},
		{Name: "SpanName", Type: field.TypeString},
		{Name: "FaultKind", Type: field.TypeString},
		{Name: "IsRoot", Type: field.TypeBool},
	}
	// OtelSpanFaultsTable holds the schema information for the "otel_span_faults" table.
	OtelSpanFaultsTable = &schema.Table{
		Name:       "otel_span_faults",
		Columns:    OtelSpanFaultsColumns,
		PrimaryKey: []*schema.Column{OtelSpanFaultsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OtelSpanFaultsTable,
	}
)

func init() {
	OtelSpanFaultsTable.Annotation = &entsql.Annotation{
		Table: "otel_span_faults",
	}
}
