// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TbSoftwareDefineColumns holds the columns for the "tb_software_define" table.
	TbSoftwareDefineColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "type", Type: field.TypeInt16},
		{Name: "span_conditions", Type: field.TypeJSON, Nullable: true},
		{Name: "is_valid", Type: field.TypeInt, Default: 1},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
	}
	// TbSoftwareDefineTable holds the schema information for the "tb_software_define" table.
	TbSoftwareDefineTable = &schema.Table{
		Name:       "tb_software_define",
		Columns:    TbSoftwareDefineColumns,
		PrimaryKey: []*schema.Column{TbSoftwareDefineColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TbSoftwareDefineTable,
	}
)

func init() {
	TbSoftwareDefineTable.Annotation = &entsql.Annotation{
		Table: "tb_software_define",
	}
}
