// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/teanoon/opentelemetry-collector-contrib/exporter/metadataexporter/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/teanoon/opentelemetry-collector-contrib/exporter/metadataexporter/ent/applicationstructure"
	"github.com/teanoon/opentelemetry-collector-contrib/exporter/metadataexporter/ent/querykey"
	"github.com/teanoon/opentelemetry-collector-contrib/exporter/metadataexporter/ent/queryvalue"
	"github.com/teanoon/opentelemetry-collector-contrib/exporter/metadataexporter/ent/systemparameter"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ApplicationStructure is the client for interacting with the ApplicationStructure builders.
	ApplicationStructure *ApplicationStructureClient
	// QueryKey is the client for interacting with the QueryKey builders.
	QueryKey *QueryKeyClient
	// QueryValue is the client for interacting with the QueryValue builders.
	QueryValue *QueryValueClient
	// SystemParameter is the client for interacting with the SystemParameter builders.
	SystemParameter *SystemParameterClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ApplicationStructure = NewApplicationStructureClient(c.config)
	c.QueryKey = NewQueryKeyClient(c.config)
	c.QueryValue = NewQueryValueClient(c.config)
	c.SystemParameter = NewSystemParameterClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		ApplicationStructure: NewApplicationStructureClient(cfg),
		QueryKey:             NewQueryKeyClient(cfg),
		QueryValue:           NewQueryValueClient(cfg),
		SystemParameter:      NewSystemParameterClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		ApplicationStructure: NewApplicationStructureClient(cfg),
		QueryKey:             NewQueryKeyClient(cfg),
		QueryValue:           NewQueryValueClient(cfg),
		SystemParameter:      NewSystemParameterClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ApplicationStructure.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ApplicationStructure.Use(hooks...)
	c.QueryKey.Use(hooks...)
	c.QueryValue.Use(hooks...)
	c.SystemParameter.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.ApplicationStructure.Intercept(interceptors...)
	c.QueryKey.Intercept(interceptors...)
	c.QueryValue.Intercept(interceptors...)
	c.SystemParameter.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ApplicationStructureMutation:
		return c.ApplicationStructure.mutate(ctx, m)
	case *QueryKeyMutation:
		return c.QueryKey.mutate(ctx, m)
	case *QueryValueMutation:
		return c.QueryValue.mutate(ctx, m)
	case *SystemParameterMutation:
		return c.SystemParameter.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ApplicationStructureClient is a client for the ApplicationStructure schema.
type ApplicationStructureClient struct {
	config
}

// NewApplicationStructureClient returns a client for the ApplicationStructure from the given config.
func NewApplicationStructureClient(c config) *ApplicationStructureClient {
	return &ApplicationStructureClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `applicationstructure.Hooks(f(g(h())))`.
func (c *ApplicationStructureClient) Use(hooks ...Hook) {
	c.hooks.ApplicationStructure = append(c.hooks.ApplicationStructure, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `applicationstructure.Intercept(f(g(h())))`.
func (c *ApplicationStructureClient) Intercept(interceptors ...Interceptor) {
	c.inters.ApplicationStructure = append(c.inters.ApplicationStructure, interceptors...)
}

// Create returns a builder for creating a ApplicationStructure entity.
func (c *ApplicationStructureClient) Create() *ApplicationStructureCreate {
	mutation := newApplicationStructureMutation(c.config, OpCreate)
	return &ApplicationStructureCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ApplicationStructure entities.
func (c *ApplicationStructureClient) CreateBulk(builders ...*ApplicationStructureCreate) *ApplicationStructureCreateBulk {
	return &ApplicationStructureCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ApplicationStructureClient) MapCreateBulk(slice any, setFunc func(*ApplicationStructureCreate, int)) *ApplicationStructureCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ApplicationStructureCreateBulk{err: fmt.Errorf("calling to ApplicationStructureClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ApplicationStructureCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ApplicationStructureCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ApplicationStructure.
func (c *ApplicationStructureClient) Update() *ApplicationStructureUpdate {
	mutation := newApplicationStructureMutation(c.config, OpUpdate)
	return &ApplicationStructureUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ApplicationStructureClient) UpdateOne(as *ApplicationStructure) *ApplicationStructureUpdateOne {
	mutation := newApplicationStructureMutation(c.config, OpUpdateOne, withApplicationStructure(as))
	return &ApplicationStructureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ApplicationStructureClient) UpdateOneID(id string) *ApplicationStructureUpdateOne {
	mutation := newApplicationStructureMutation(c.config, OpUpdateOne, withApplicationStructureID(id))
	return &ApplicationStructureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ApplicationStructure.
func (c *ApplicationStructureClient) Delete() *ApplicationStructureDelete {
	mutation := newApplicationStructureMutation(c.config, OpDelete)
	return &ApplicationStructureDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ApplicationStructureClient) DeleteOne(as *ApplicationStructure) *ApplicationStructureDeleteOne {
	return c.DeleteOneID(as.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ApplicationStructureClient) DeleteOneID(id string) *ApplicationStructureDeleteOne {
	builder := c.Delete().Where(applicationstructure.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ApplicationStructureDeleteOne{builder}
}

// Query returns a query builder for ApplicationStructure.
func (c *ApplicationStructureClient) Query() *ApplicationStructureQuery {
	return &ApplicationStructureQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeApplicationStructure},
		inters: c.Interceptors(),
	}
}

// Get returns a ApplicationStructure entity by its id.
func (c *ApplicationStructureClient) Get(ctx context.Context, id string) (*ApplicationStructure, error) {
	return c.Query().Where(applicationstructure.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ApplicationStructureClient) GetX(ctx context.Context, id string) *ApplicationStructure {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ApplicationStructureClient) Hooks() []Hook {
	return c.hooks.ApplicationStructure
}

// Interceptors returns the client interceptors.
func (c *ApplicationStructureClient) Interceptors() []Interceptor {
	return c.inters.ApplicationStructure
}

func (c *ApplicationStructureClient) mutate(ctx context.Context, m *ApplicationStructureMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ApplicationStructureCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ApplicationStructureUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ApplicationStructureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ApplicationStructureDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ApplicationStructure mutation op: %q", m.Op())
	}
}

// QueryKeyClient is a client for the QueryKey schema.
type QueryKeyClient struct {
	config
}

// NewQueryKeyClient returns a client for the QueryKey from the given config.
func NewQueryKeyClient(c config) *QueryKeyClient {
	return &QueryKeyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `querykey.Hooks(f(g(h())))`.
func (c *QueryKeyClient) Use(hooks ...Hook) {
	c.hooks.QueryKey = append(c.hooks.QueryKey, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `querykey.Intercept(f(g(h())))`.
func (c *QueryKeyClient) Intercept(interceptors ...Interceptor) {
	c.inters.QueryKey = append(c.inters.QueryKey, interceptors...)
}

// Create returns a builder for creating a QueryKey entity.
func (c *QueryKeyClient) Create() *QueryKeyCreate {
	mutation := newQueryKeyMutation(c.config, OpCreate)
	return &QueryKeyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of QueryKey entities.
func (c *QueryKeyClient) CreateBulk(builders ...*QueryKeyCreate) *QueryKeyCreateBulk {
	return &QueryKeyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *QueryKeyClient) MapCreateBulk(slice any, setFunc func(*QueryKeyCreate, int)) *QueryKeyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &QueryKeyCreateBulk{err: fmt.Errorf("calling to QueryKeyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*QueryKeyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &QueryKeyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for QueryKey.
func (c *QueryKeyClient) Update() *QueryKeyUpdate {
	mutation := newQueryKeyMutation(c.config, OpUpdate)
	return &QueryKeyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *QueryKeyClient) UpdateOne(qk *QueryKey) *QueryKeyUpdateOne {
	mutation := newQueryKeyMutation(c.config, OpUpdateOne, withQueryKey(qk))
	return &QueryKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *QueryKeyClient) UpdateOneID(id int64) *QueryKeyUpdateOne {
	mutation := newQueryKeyMutation(c.config, OpUpdateOne, withQueryKeyID(id))
	return &QueryKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for QueryKey.
func (c *QueryKeyClient) Delete() *QueryKeyDelete {
	mutation := newQueryKeyMutation(c.config, OpDelete)
	return &QueryKeyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *QueryKeyClient) DeleteOne(qk *QueryKey) *QueryKeyDeleteOne {
	return c.DeleteOneID(qk.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *QueryKeyClient) DeleteOneID(id int64) *QueryKeyDeleteOne {
	builder := c.Delete().Where(querykey.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &QueryKeyDeleteOne{builder}
}

// Query returns a query builder for QueryKey.
func (c *QueryKeyClient) Query() *QueryKeyQuery {
	return &QueryKeyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeQueryKey},
		inters: c.Interceptors(),
	}
}

// Get returns a QueryKey entity by its id.
func (c *QueryKeyClient) Get(ctx context.Context, id int64) (*QueryKey, error) {
	return c.Query().Where(querykey.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *QueryKeyClient) GetX(ctx context.Context, id int64) *QueryKey {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryValues queries the values edge of a QueryKey.
func (c *QueryKeyClient) QueryValues(qk *QueryKey) *QueryValueQuery {
	query := (&QueryValueClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := qk.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(querykey.Table, querykey.FieldID, id),
			sqlgraph.To(queryvalue.Table, queryvalue.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, querykey.ValuesTable, querykey.ValuesColumn),
		)
		fromV = sqlgraph.Neighbors(qk.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *QueryKeyClient) Hooks() []Hook {
	return c.hooks.QueryKey
}

// Interceptors returns the client interceptors.
func (c *QueryKeyClient) Interceptors() []Interceptor {
	return c.inters.QueryKey
}

func (c *QueryKeyClient) mutate(ctx context.Context, m *QueryKeyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&QueryKeyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&QueryKeyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&QueryKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&QueryKeyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown QueryKey mutation op: %q", m.Op())
	}
}

// QueryValueClient is a client for the QueryValue schema.
type QueryValueClient struct {
	config
}

// NewQueryValueClient returns a client for the QueryValue from the given config.
func NewQueryValueClient(c config) *QueryValueClient {
	return &QueryValueClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `queryvalue.Hooks(f(g(h())))`.
func (c *QueryValueClient) Use(hooks ...Hook) {
	c.hooks.QueryValue = append(c.hooks.QueryValue, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `queryvalue.Intercept(f(g(h())))`.
func (c *QueryValueClient) Intercept(interceptors ...Interceptor) {
	c.inters.QueryValue = append(c.inters.QueryValue, interceptors...)
}

// Create returns a builder for creating a QueryValue entity.
func (c *QueryValueClient) Create() *QueryValueCreate {
	mutation := newQueryValueMutation(c.config, OpCreate)
	return &QueryValueCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of QueryValue entities.
func (c *QueryValueClient) CreateBulk(builders ...*QueryValueCreate) *QueryValueCreateBulk {
	return &QueryValueCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *QueryValueClient) MapCreateBulk(slice any, setFunc func(*QueryValueCreate, int)) *QueryValueCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &QueryValueCreateBulk{err: fmt.Errorf("calling to QueryValueClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*QueryValueCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &QueryValueCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for QueryValue.
func (c *QueryValueClient) Update() *QueryValueUpdate {
	mutation := newQueryValueMutation(c.config, OpUpdate)
	return &QueryValueUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *QueryValueClient) UpdateOne(qv *QueryValue) *QueryValueUpdateOne {
	mutation := newQueryValueMutation(c.config, OpUpdateOne, withQueryValue(qv))
	return &QueryValueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *QueryValueClient) UpdateOneID(id int64) *QueryValueUpdateOne {
	mutation := newQueryValueMutation(c.config, OpUpdateOne, withQueryValueID(id))
	return &QueryValueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for QueryValue.
func (c *QueryValueClient) Delete() *QueryValueDelete {
	mutation := newQueryValueMutation(c.config, OpDelete)
	return &QueryValueDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *QueryValueClient) DeleteOne(qv *QueryValue) *QueryValueDeleteOne {
	return c.DeleteOneID(qv.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *QueryValueClient) DeleteOneID(id int64) *QueryValueDeleteOne {
	builder := c.Delete().Where(queryvalue.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &QueryValueDeleteOne{builder}
}

// Query returns a query builder for QueryValue.
func (c *QueryValueClient) Query() *QueryValueQuery {
	return &QueryValueQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeQueryValue},
		inters: c.Interceptors(),
	}
}

// Get returns a QueryValue entity by its id.
func (c *QueryValueClient) Get(ctx context.Context, id int64) (*QueryValue, error) {
	return c.Query().Where(queryvalue.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *QueryValueClient) GetX(ctx context.Context, id int64) *QueryValue {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryKey queries the key edge of a QueryValue.
func (c *QueryValueClient) QueryKey(qv *QueryValue) *QueryKeyQuery {
	query := (&QueryKeyClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := qv.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(queryvalue.Table, queryvalue.FieldID, id),
			sqlgraph.To(querykey.Table, querykey.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, queryvalue.KeyTable, queryvalue.KeyColumn),
		)
		fromV = sqlgraph.Neighbors(qv.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *QueryValueClient) Hooks() []Hook {
	return c.hooks.QueryValue
}

// Interceptors returns the client interceptors.
func (c *QueryValueClient) Interceptors() []Interceptor {
	return c.inters.QueryValue
}

func (c *QueryValueClient) mutate(ctx context.Context, m *QueryValueMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&QueryValueCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&QueryValueUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&QueryValueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&QueryValueDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown QueryValue mutation op: %q", m.Op())
	}
}

// SystemParameterClient is a client for the SystemParameter schema.
type SystemParameterClient struct {
	config
}

// NewSystemParameterClient returns a client for the SystemParameter from the given config.
func NewSystemParameterClient(c config) *SystemParameterClient {
	return &SystemParameterClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `systemparameter.Hooks(f(g(h())))`.
func (c *SystemParameterClient) Use(hooks ...Hook) {
	c.hooks.SystemParameter = append(c.hooks.SystemParameter, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `systemparameter.Intercept(f(g(h())))`.
func (c *SystemParameterClient) Intercept(interceptors ...Interceptor) {
	c.inters.SystemParameter = append(c.inters.SystemParameter, interceptors...)
}

// Create returns a builder for creating a SystemParameter entity.
func (c *SystemParameterClient) Create() *SystemParameterCreate {
	mutation := newSystemParameterMutation(c.config, OpCreate)
	return &SystemParameterCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SystemParameter entities.
func (c *SystemParameterClient) CreateBulk(builders ...*SystemParameterCreate) *SystemParameterCreateBulk {
	return &SystemParameterCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SystemParameterClient) MapCreateBulk(slice any, setFunc func(*SystemParameterCreate, int)) *SystemParameterCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SystemParameterCreateBulk{err: fmt.Errorf("calling to SystemParameterClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SystemParameterCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SystemParameterCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SystemParameter.
func (c *SystemParameterClient) Update() *SystemParameterUpdate {
	mutation := newSystemParameterMutation(c.config, OpUpdate)
	return &SystemParameterUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SystemParameterClient) UpdateOne(sp *SystemParameter) *SystemParameterUpdateOne {
	mutation := newSystemParameterMutation(c.config, OpUpdateOne, withSystemParameter(sp))
	return &SystemParameterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SystemParameterClient) UpdateOneID(id string) *SystemParameterUpdateOne {
	mutation := newSystemParameterMutation(c.config, OpUpdateOne, withSystemParameterID(id))
	return &SystemParameterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SystemParameter.
func (c *SystemParameterClient) Delete() *SystemParameterDelete {
	mutation := newSystemParameterMutation(c.config, OpDelete)
	return &SystemParameterDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SystemParameterClient) DeleteOne(sp *SystemParameter) *SystemParameterDeleteOne {
	return c.DeleteOneID(sp.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SystemParameterClient) DeleteOneID(id string) *SystemParameterDeleteOne {
	builder := c.Delete().Where(systemparameter.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SystemParameterDeleteOne{builder}
}

// Query returns a query builder for SystemParameter.
func (c *SystemParameterClient) Query() *SystemParameterQuery {
	return &SystemParameterQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSystemParameter},
		inters: c.Interceptors(),
	}
}

// Get returns a SystemParameter entity by its id.
func (c *SystemParameterClient) Get(ctx context.Context, id string) (*SystemParameter, error) {
	return c.Query().Where(systemparameter.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SystemParameterClient) GetX(ctx context.Context, id string) *SystemParameter {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SystemParameterClient) Hooks() []Hook {
	return c.hooks.SystemParameter
}

// Interceptors returns the client interceptors.
func (c *SystemParameterClient) Interceptors() []Interceptor {
	return c.inters.SystemParameter
}

func (c *SystemParameterClient) mutate(ctx context.Context, m *SystemParameterMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SystemParameterCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SystemParameterUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SystemParameterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SystemParameterDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SystemParameter mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ApplicationStructure, QueryKey, QueryValue, SystemParameter []ent.Hook
	}
	inters struct {
		ApplicationStructure, QueryKey, QueryValue, SystemParameter []ent.Interceptor
	}
)
