// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teanoon/opentelemetry-collector-contrib/processor/faultkindprocessor/ent/predicate"
	"github.com/teanoon/opentelemetry-collector-contrib/processor/faultkindprocessor/ent/schema"
	"github.com/teanoon/opentelemetry-collector-contrib/processor/faultkindprocessor/ent/systemparameter"
)

// SystemParameterUpdate is the builder for updating SystemParameter entities.
type SystemParameterUpdate struct {
	config
	hooks    []Hook
	mutation *SystemParameterMutation
}

// Where appends a list predicates to the SystemParameterUpdate builder.
func (spu *SystemParameterUpdate) Where(ps ...predicate.SystemParameter) *SystemParameterUpdate {
	spu.mutation.Where(ps...)
	return spu
}

// SetValue sets the "value" field.
func (spu *SystemParameterUpdate) SetValue(skd *schema.FaultKindDefinitions) *SystemParameterUpdate {
	spu.mutation.SetValue(skd)
	return spu
}

// Mutation returns the SystemParameterMutation object of the builder.
func (spu *SystemParameterUpdate) Mutation() *SystemParameterMutation {
	return spu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (spu *SystemParameterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, spu.sqlSave, spu.mutation, spu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (spu *SystemParameterUpdate) SaveX(ctx context.Context) int {
	affected, err := spu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (spu *SystemParameterUpdate) Exec(ctx context.Context) error {
	_, err := spu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (spu *SystemParameterUpdate) ExecX(ctx context.Context) {
	if err := spu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (spu *SystemParameterUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(systemparameter.Table, systemparameter.Columns, sqlgraph.NewFieldSpec(systemparameter.FieldID, field.TypeString))
	if ps := spu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := spu.mutation.Value(); ok {
		_spec.SetField(systemparameter.FieldValue, field.TypeOther, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, spu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemparameter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	spu.mutation.done = true
	return n, nil
}

// SystemParameterUpdateOne is the builder for updating a single SystemParameter entity.
type SystemParameterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemParameterMutation
}

// SetValue sets the "value" field.
func (spuo *SystemParameterUpdateOne) SetValue(skd *schema.FaultKindDefinitions) *SystemParameterUpdateOne {
	spuo.mutation.SetValue(skd)
	return spuo
}

// Mutation returns the SystemParameterMutation object of the builder.
func (spuo *SystemParameterUpdateOne) Mutation() *SystemParameterMutation {
	return spuo.mutation
}

// Where appends a list predicates to the SystemParameterUpdate builder.
func (spuo *SystemParameterUpdateOne) Where(ps ...predicate.SystemParameter) *SystemParameterUpdateOne {
	spuo.mutation.Where(ps...)
	return spuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (spuo *SystemParameterUpdateOne) Select(field string, fields ...string) *SystemParameterUpdateOne {
	spuo.fields = append([]string{field}, fields...)
	return spuo
}

// Save executes the query and returns the updated SystemParameter entity.
func (spuo *SystemParameterUpdateOne) Save(ctx context.Context) (*SystemParameter, error) {
	return withHooks(ctx, spuo.sqlSave, spuo.mutation, spuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (spuo *SystemParameterUpdateOne) SaveX(ctx context.Context) *SystemParameter {
	node, err := spuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (spuo *SystemParameterUpdateOne) Exec(ctx context.Context) error {
	_, err := spuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (spuo *SystemParameterUpdateOne) ExecX(ctx context.Context) {
	if err := spuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (spuo *SystemParameterUpdateOne) sqlSave(ctx context.Context) (_node *SystemParameter, err error) {
	_spec := sqlgraph.NewUpdateSpec(systemparameter.Table, systemparameter.Columns, sqlgraph.NewFieldSpec(systemparameter.FieldID, field.TypeString))
	id, ok := spuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemParameter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := spuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemparameter.FieldID)
		for _, f := range fields {
			if !systemparameter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemparameter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := spuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := spuo.mutation.Value(); ok {
		_spec.SetField(systemparameter.FieldValue, field.TypeOther, value)
	}
	_node = &SystemParameter{config: spuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, spuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemparameter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	spuo.mutation.done = true
	return _node, nil
}
