// Code generated by ent, DO NOT EDIT.

package applicationstructure

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the applicationstructure type in the database.
	Label = "application_structure"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "code"
	// FieldParentCode holds the string denoting the parentcode field in the database.
	FieldParentCode = "parent_code"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldValidDate holds the string denoting the valid_date field in the database.
	FieldValidDate = "valid_date"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// Table holds the table name of the applicationstructure in the database.
	Table = "tb_application_structure"
)

// Columns holds all SQL columns for applicationstructure fields.
var Columns = []string{
	FieldID,
	FieldParentCode,
	FieldLevel,
	FieldValidDate,
	FieldCreateTime,
	FieldUpdateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ParentCodeValidator is a validator for the "parentCode" field. It is called by the builders before save.
	ParentCodeValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the ApplicationStructure queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByParentCode orders the results by the parentCode field.
func ByParentCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentCode, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByValidDate orders the results by the valid_date field.
func ByValidDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidDate, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}
