// Code generated by ent, DO NOT EDIT.

package exceptioncategory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/exceptionprocessor/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldEQ(FieldName, v))
}

// IsValid applies equality check predicate on the "is_valid" field. It's identical to IsValidEQ.
func IsValid(v int) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldEQ(FieldIsValid, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldEQ(FieldUpdateTime, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldContainsFold(FieldName, v))
}

// IsValidEQ applies the EQ predicate on the "is_valid" field.
func IsValidEQ(v int) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldEQ(FieldIsValid, v))
}

// IsValidNEQ applies the NEQ predicate on the "is_valid" field.
func IsValidNEQ(v int) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldNEQ(FieldIsValid, v))
}

// IsValidIn applies the In predicate on the "is_valid" field.
func IsValidIn(vs ...int) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldIn(FieldIsValid, vs...))
}

// IsValidNotIn applies the NotIn predicate on the "is_valid" field.
func IsValidNotIn(vs ...int) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldNotIn(FieldIsValid, vs...))
}

// IsValidGT applies the GT predicate on the "is_valid" field.
func IsValidGT(v int) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldGT(FieldIsValid, v))
}

// IsValidGTE applies the GTE predicate on the "is_valid" field.
func IsValidGTE(v int) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldGTE(FieldIsValid, v))
}

// IsValidLT applies the LT predicate on the "is_valid" field.
func IsValidLT(v int) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldLT(FieldIsValid, v))
}

// IsValidLTE applies the LTE predicate on the "is_valid" field.
func IsValidLTE(v int) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldLTE(FieldIsValid, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.FieldLTE(FieldUpdateTime, v))
}

// HasExceptionDefinitions applies the HasEdge predicate on the "exception_definitions" edge.
func HasExceptionDefinitions() predicate.ExceptionCategory {
	return predicate.ExceptionCategory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExceptionDefinitionsTable, ExceptionDefinitionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExceptionDefinitionsWith applies the HasEdge predicate on the "exception_definitions" edge with a given conditions (other predicates).
func HasExceptionDefinitionsWith(preds ...predicate.ExceptionDefinition) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(func(s *sql.Selector) {
		step := newExceptionDefinitionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExceptionCategory) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExceptionCategory) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExceptionCategory) predicate.ExceptionCategory {
	return predicate.ExceptionCategory(sql.NotPredicates(p))
}
