// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ApplicationStructure is the predicate function for applicationstructure builders.
type ApplicationStructure func(*sql.Selector)

// QueryKey is the predicate function for querykey builders.
type QueryKey func(*sql.Selector)

// QueryValue is the predicate function for queryvalue builders.
type QueryValue func(*sql.Selector)
